### ISSUE TITLE
ota update

### ISSUE THREAD

**Issue by mrdsn3** [shkoo/MeshGnome#1]
hi shkoo thanks for this  useful library  I INSTALL it and try to run examples  but get this error  ? why librrary dont add ?

MeshSyncStruct.h: No such file or directory

**Comment by mrdsn3** [comment]
I added manually  and fix it but now give this error 

'class MeshSyncMem' has no member named 'localMetadataBufferLen'

**Comment by mrdsn3** [comment]
I convert this part of code to comment and code compiling don 
`
  assertEqual(sync1->v1, 5);
  assertEqual(sync1->v2, 23UL);
  assertEqual(sync2->v1, 5);
  assertEqual(sync2->v2, 23UL);

  assertEqual(sync1.localVersion(), sync2.localVersion());*/`
and this part 
`
  //assertEqual(memsync.localMetadata(), "Md");
  //assertEqual(memsync.localData(), "D");

 // assertEqual(memsync.localMetadataBufferLen(), 2UL);
  //assertEqual(0, memcmp(memsync.localMetadataBuffer(), "Md", 2));

  //assertEqual(memsync.localDataBufferLen(), 1UL);
  //assertEqual(0, memcmp(memsync.localDataBuffer(), "D", 1));`
how I can edit  this part of MeshSyncTest for well working?

**Comment by mrdsn3** [comment]
and how we can send another sketch update from spiffs

**Comment by mrdsn3** [comment]
I wana develope this liib for ota updating such as httpupdater  can U give me som  advise 

wich variable contain  skecht?

**Comment by shkoo** [comment]
Hi,
I've released MeshGnome 1.1.1 which should fix these problems, and the example is a bit more polished.
